import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

      <main>
        <Poster />
        <Heading title="О нас" />
        <Text text="Своей глобальной задачей мы видим развитие и популяризацию скалолазания не только как спорта, но как приятного досуга, как повода и средства общения между людьми. Наши скалодромы - это целый мир уникального личного опыта и комфортная среда для общения между нашими гостями." />
        {/* <Vote /> */}
        <Benefits />
        <Heading title="Наш скалодром" />
        <Text text="Уютный и современный скалодром, где в любое время Вы можете почувствовать себя как дома" />
        <Photo />
        <Heading title="Никогда не были на скалодроме? Тогда мы ждём вас!" />
        
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
